#!/bin/bash
#
# Create some links to make running tests inside the Eclipse debugger easier.
#
# The links stitch together the directory structure that the Parasol compiler expects to be in place by default:
#
#    <INSTALL DIRECTORY>
#        bin - The directory containing scripts plus the installed binaries for both Linux and Windows
#        compiler - Contains the main Parasol command-line compiler file 'main.p'.
#        lib - Contains the source to the Parasol runtime root.p root scope file.
#        src/lib - The sources to the Parasol runtime.
#        src/util - The sources for Parasol utility programs referenced from scripts in the bin directory.
#        test/drivers - The program the runs the test validation suite.
#        test/scripts - The test script files.
#        test/src - Parasol source files referenced from test scripts.
#
# In addition, the following directory is used to build a test version of parasolrt:
#
#        Default - The build directory (not present in a binary install).
#
# Because the parasolrt binary expects to run under the install directory, the above arrangement mimics an install
# well enough.
#
set -e

PARASOL_BIN=$(dirname `readlink -f $0`)/..
export PARASOL_HOME=`readlink -f $PARASOL_BIN`

ln -sfT $PARASOL_HOME/bin $PARASOL_HOME/z_linux/bin
ln -sfT $PARASOL_HOME/compiler $PARASOL_HOME/z_linux/compiler
ln -sfT $PARASOL_HOME/lib $PARASOL_HOME/z_linux/lib
ln -sfT $PARASOL_HOME/src $PARASOL_HOME/z_linux/src
ln -sfT $PARASOL_HOME/test $PARASOL_HOME/z_linux/test
 
