#!/bin/bash

set -e

SCRIPT_LOC=$(dirname "`readlink -f \"$0\"`")/..
export PARASOL_HOME=`readlink -f "$SCRIPT_LOC"`

#   Copyright 2015 Robert Jervis
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

if [ "$1x" == "x" ]
then
    echo Use is: gen_documents '<output-directory>'
	exit 1
fi
cd $PARASOL_HOME
pbuild
pcontext create -p docs
export PARASOL_CONTEXT=docs
pcontext install build/build_parasollanguage.org
pcontext install build/debug_parasollanguage.org
paradoc -c $PARASOL_HOME/doc/parasol -h Parasol $1 core:parasollanguage.org build:parasollanguage.org debug:parasollanguage.org

