#!/bin/bash

set -e

SCRIPT_LOC=$(dirname "`readlink -f \"$0\"`")/..
export PARASOL_HOME=`readlink -f "$SCRIPT_LOC"`

#   Copyright 2015 Robert Jervis
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

if [ "$1x" == "x" ]
then
    echo Use is: gen_documents '<output-directory>'
	exit 1
fi
cd $PARASOL_HOME/..
pbuild
pcontext create -p docs
export PARASOL_CONTEXT=docs
if ! ( pcontext install parasol/build/core_parasollanguage.org )
then
	echo Installation failed for core:parasollanguage.org - ignoring
fi
if ! ( pcontext install parasol/build/build_parasollanguage.org )
then
	echo Installation failed for build:parasollanguage.org - ignoring
fi
if ! ( pcontext install parasol/build/debug_parasollanguage.org )
then
    echo Installation failed for debug:parasollanguage.org - ignoring
fi
if ! ( pcontext install parasol/build/documentation_parasollanguage.org )
then
    echo Installation failed for documentation:parasollanguage.org - ignoring
fi
if ! ( pcontext install parasol/build/tty_parasollanguage.org )
then
    echo Installation failed for tty:parasollanguage.org - ignoring
fi

if ! ( pcontext install wizard-common/build/common_wizardsystemssoftware.com )
then
    echo Installation failed for common:wizardsystemssoftware.com - ignoring
fi
if ! ( pcontext install alys/build/alys-client_wizardsystemssoftware.com )
then
    echo Installation failed for alys-client:wizardsystemssoftware.com - ignoring
fi
if ! ( pcontext install alys/build/alys-lib_wizardsystemssoftware.com )
then
    echo Installation failed for alys-lib:wizardsystemssoftware.com - ignoring
fi
if ! ( pcontext install imagine/build/editor_wizardsystemssoftware.com )
then
    echo Installation failed for editor:wizardsystemssoftware.com - ignoring
fi
paradoc -c $PARASOL_HOME/doc/parasol -h Parasol -f $1 core:parasollanguage.org \
				build:parasollanguage.org \
				debug:parasollanguage.org \
				documentation:parasollanguage.org \
				tty:parasollanguage.org \
				debug:parasollanguage.org \
				common:wizardsystemssoftware.com \
				alys-client:wizardsystemssoftware.com \
				alys-lib:wizardsystemssoftware.com \
				editor:wizardsystemssoftware.com

